classdef EphData
    properties
        PRN;
		sT;GPSTime;weekno;
		af0,af1,af2;
		Iode;
		Crs,Crc,Cus,Cuc,Cis,Cic;
		dn,m0,ecc;
		Asqrt;
		Toe;
		Omega0;
		I0;
		w;
		Omegadot
		Idot;
		L2Code;
		ps;
		L2P;
		Ura;
		SV_health;
		Tgd;
		Iodc;
		Ttime;
		other;
    end
    
    methods
        function a = EphData(varargin)
            if(nargin==1)
                a.PRN=0;
                a.sT=Time(0);a.GPSTime=0;a.weekno=0;
                a.af0=0;a.af1=0;a.af2=0;
                a.Iode=0;
                a.Crs=0;a.Crc=0;a.Cus=0;a.Cuc=0;a.Cis=0;a.Cic=0;
                a.dn=0;a.m0=0;a.ecc=0;
                a.Asqrt=0;
                a.Toe=0;
                a.Omega0=0;
                a.I0=0;
                a.w=0;
                a.Omegadot=0;
                a.Idot=0;
                a.L2Code=0;
                a.ps=0;
                a.L2P=0;
                a.Ura=0;
                a.SV_health=0;
                a.Tgd=0;
                a.Iodc=0;
                a.Ttime=0;
                a.other=0;
            end
        end
     end
end